require: rubocop-performance

AllCops:
  Exclude:
    - db/schema.rb

Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
